.PHONY: clean

CXX=g++
CXXFLAGS=-Wall -std=c++11
OPTFLAGS=-O3 

EXE_NAME=membles

SRC = $(wildcard *.cpp)
OBJ = $(addsuffix .o, $(basename $(SRC)))

REBUILDABLES=$(OBJ) $(EXE_NAME)

all: ${EXE_NAME}

#   $@ target name, $^ target deps, $< matched pattern
$(EXE_NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^ 
	@echo "Built $@ successfully" 

#include the autogenerated dependency files for each .o file
-include $(OBJ:.o=.dep)

# build dependency list via gcc -M and save to a .dep file
%.dep : %.cpp
	@$(CXX) -M $(CXXFLAGS) $< > $@

# build all .cpp files to .o files
%.o : %.cpp
	$(CXX) $(CXXFLAGS) -o $@ -c $<


clean: 
	-rm -f $(REBUILDABLES) *.dep *.deppo
# DO NOT DELETE
